// ─── Personality Report PDF Export ─────────────────────────────────────────────
// Generates a professional PDF from the personality prediction markdown report.
// Uses jsPDF directly (no html2canvas) for crisp, text-selectable output.

/**
 * Exports the personality report as a downloadable PDF.
 *
 * @param {string} markdownContent - Raw markdown string from the AI analysis
 * @param {string} userName - The user's name displayed on the report
 * @returns {Promise<void>}
 */
export async function exportPersonalityPDF(markdownContent, userName) {
  if (typeof window === "undefined") return;

  const { jsPDF } = await import("jspdf");

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // ─── Layout Constants ────────────────────────────────────────────────
  const PAGE_WIDTH = pdf.internal.pageSize.getWidth(); // 210mm
  const PAGE_HEIGHT = pdf.internal.pageSize.getHeight(); // 297mm
  const MARGIN_LEFT = 20;
  const MARGIN_RIGHT = 20;
  const MARGIN_TOP = 25;
  const MARGIN_BOTTOM = 25;
  const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
  const MAX_Y = PAGE_HEIGHT - MARGIN_BOTTOM;

  // ─── Colors ──────────────────────────────────────────────────────────
  const COLOR_PRIMARY = [107, 33, 168]; // Purple-700
  const COLOR_HEADING = [30, 30, 30]; // Near-black
  const COLOR_BODY = [55, 65, 81]; // Gray-700
  const COLOR_MUTED = [107, 114, 128]; // Gray-500
  const COLOR_ACCENT_LINE = [168, 85, 247]; // Purple-500
  const COLOR_BULLET = [147, 51, 234]; // Purple-600

  let currentY = MARGIN_TOP;
  let pageNumber = 1;

  // ─── Helper: Add Page Footer ─────────────────────────────────────────
  function addPageFooter() {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...COLOR_MUTED);
    pdf.text(
      `Page ${pageNumber}`,
      PAGE_WIDTH / 2,
      PAGE_HEIGHT - 12,
      { align: "center" }
    );
    pdf.text(
      "Generated by Rezumix",
      PAGE_WIDTH - MARGIN_RIGHT,
      PAGE_HEIGHT - 12,
      { align: "right" }
    );
  }

  // ─── Helper: Check for Page Break ────────────────────────────────────
  function ensureSpace(requiredHeight) {
    if (currentY + requiredHeight > MAX_Y) {
      addPageFooter();
      pdf.addPage();
      pageNumber++;
      currentY = MARGIN_TOP;
    }
  }

  // ─── Helper: Render Wrapped Text ─────────────────────────────────────
  function renderWrappedText(text, x, fontSize, fontStyle, color, lineHeight) {
    pdf.setFont("helvetica", fontStyle);
    pdf.setFontSize(fontSize);
    pdf.setTextColor(...color);

    const lines = pdf.splitTextToSize(text, CONTENT_WIDTH - (x - MARGIN_LEFT));
    for (const line of lines) {
      ensureSpace(lineHeight);
      pdf.text(line, x, currentY);
      currentY += lineHeight;
    }
  }

  // ─── Header Section ──────────────────────────────────────────────────
  // Accent bar at the top
  pdf.setFillColor(...COLOR_ACCENT_LINE);
  pdf.rect(0, 0, PAGE_WIDTH, 3, "F");

  // Title
  currentY = 20;
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.setTextColor(...COLOR_PRIMARY);
  pdf.text("Personality Assessment Report", MARGIN_LEFT, currentY);
  currentY += 10;

  // User name
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(13);
  pdf.setTextColor(...COLOR_HEADING);
  pdf.text(`Prepared for: ${userName}`, MARGIN_LEFT, currentY);
  currentY += 7;

  // Date and time
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });
  pdf.setFontSize(10);
  pdf.setTextColor(...COLOR_MUTED);
  pdf.text(`Generated on ${dateStr} at ${timeStr}`, MARGIN_LEFT, currentY);
  currentY += 4;

  // Separator line
  pdf.setDrawColor(...COLOR_ACCENT_LINE);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN_LEFT, currentY, PAGE_WIDTH - MARGIN_RIGHT, currentY);
  currentY += 10;

  // ─── Parse Markdown into Sections ────────────────────────────────────
  const lines = markdownContent.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Skip empty lines (add small spacing)
    if (!trimmed) {
      currentY += 3;
      continue;
    }

    // ── H1 Heading (# ...) ──────────────────────────────────────────
    if (trimmed.startsWith("# ") && !trimmed.startsWith("## ")) {
      const headingText = trimmed.replace(/^#\s+/, "").replace(/\*\*/g, "");
      ensureSpace(14);
      currentY += 4;
      renderWrappedText(headingText, MARGIN_LEFT, 18, "bold", COLOR_PRIMARY, 8);
      currentY += 3;
      continue;
    }

    // ── H2 Heading (## ...) ─────────────────────────────────────────
    if (trimmed.startsWith("## ") && !trimmed.startsWith("### ")) {
      const headingText = trimmed.replace(/^##\s+/, "").replace(/\*\*/g, "");
      ensureSpace(14);
      currentY += 5;

      // Accent indicator bar before section heading
      pdf.setFillColor(...COLOR_ACCENT_LINE);
      pdf.rect(MARGIN_LEFT, currentY - 4, 3, 7, "F");

      renderWrappedText(headingText, MARGIN_LEFT + 7, 14, "bold", COLOR_HEADING, 7);
      currentY += 2;
      continue;
    }

    // ── H3 Heading (### ...) ────────────────────────────────────────
    if (trimmed.startsWith("### ")) {
      const headingText = trimmed.replace(/^###\s+/, "").replace(/\*\*/g, "");
      ensureSpace(12);
      currentY += 3;
      renderWrappedText(headingText, MARGIN_LEFT, 12, "bold", COLOR_HEADING, 6);
      currentY += 2;
      continue;
    }

    // ── H4 Heading (#### ...) ───────────────────────────────────────
    if (trimmed.startsWith("#### ")) {
      const headingText = trimmed.replace(/^####\s+/, "").replace(/\*\*/g, "");
      ensureSpace(10);
      currentY += 2;
      renderWrappedText(headingText, MARGIN_LEFT, 11, "bold", COLOR_HEADING, 6);
      currentY += 1;
      continue;
    }

    // ── Horizontal rule (---) ───────────────────────────────────────
    if (/^[-*_]{3,}$/.test(trimmed)) {
      ensureSpace(8);
      currentY += 3;
      pdf.setDrawColor(220, 220, 220);
      pdf.setLineWidth(0.3);
      pdf.line(MARGIN_LEFT, currentY, PAGE_WIDTH - MARGIN_RIGHT, currentY);
      currentY += 5;
      continue;
    }

    // ── Bullet points (- ... or * ...) ──────────────────────────────
    if (/^[-*]\s+/.test(trimmed)) {
      const bulletText = trimmed
        .replace(/^[-*]\s+/, "")
        .replace(/\*\*/g, "");
      ensureSpace(8);

      // Draw bullet dot
      pdf.setFillColor(...COLOR_BULLET);
      pdf.circle(MARGIN_LEFT + 3, currentY - 1.5, 1, "F");

      renderWrappedText(bulletText, MARGIN_LEFT + 8, 10, "normal", COLOR_BODY, 5);
      currentY += 1;
      continue;
    }

    // ── Numbered list (1. ...) ──────────────────────────────────────
    if (/^\d+\.\s+/.test(trimmed)) {
      const match = trimmed.match(/^(\d+)\.\s+(.*)/);
      if (match) {
        const num = match[1];
        const itemText = match[2].replace(/\*\*/g, "");
        ensureSpace(8);

        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(10);
        pdf.setTextColor(...COLOR_BULLET);
        pdf.text(`${num}.`, MARGIN_LEFT + 1, currentY);

        renderWrappedText(itemText, MARGIN_LEFT + 8, 10, "normal", COLOR_BODY, 5);
        currentY += 1;
      }
      continue;
    }

    // ── Blockquote (> ...) ──────────────────────────────────────────
    if (trimmed.startsWith("> ")) {
      const quoteText = trimmed.replace(/^>\s+/, "").replace(/\*\*/g, "");
      ensureSpace(10);

      // Quote accent bar
      pdf.setFillColor(230, 220, 250);
      pdf.rect(MARGIN_LEFT, currentY - 4, CONTENT_WIDTH, 10, "F");
      pdf.setFillColor(...COLOR_ACCENT_LINE);
      pdf.rect(MARGIN_LEFT, currentY - 4, 2, 10, "F");

      renderWrappedText(quoteText, MARGIN_LEFT + 6, 10, "italic", COLOR_BODY, 5);
      currentY += 2;
      continue;
    }

    // ── Regular paragraph text ──────────────────────────────────────
    const cleanText = trimmed.replace(/\*\*/g, "");
    renderWrappedText(cleanText, MARGIN_LEFT, 10, "normal", COLOR_BODY, 5);
    currentY += 2;
  }

  // ─── Final Page Footer ───────────────────────────────────────────────
  addPageFooter();

  // ─── Save the PDF ────────────────────────────────────────────────────
  const safeFileName = userName.replace(/\s+/g, "_").replace(/[^a-zA-Z0-9_]/g, "");
  pdf.save(`${safeFileName}_Personality_Report.pdf`);
}
